### ISSUE TITLE
When building from source, built package is not booting.

### ISSUE THREAD

**Issue by RobertZenz** [mt8163/android_device_bq_freezerfhd#2]
When I compile from source (according to the referenced build manual), the built package cannot boot. It hangs on the bq bootloader screen and through `adb logcat` I can see that it hangs in a boot loop and spews a lot of messages like these:

    cannot locate symbol "__xlog_buf_printf" referenced by "..."

A more complete [output can be found in this pastebin](https://pastebin.com/Fmn6ukSG).

My guess is that something in the build environment is missing, but I have a hard time figuring out what it might be. Any ideas?

**Comment by RobertZenz** [comment]
Are the build instructions up-to-date? I retried using the mt1863/android repository instead

    repo init -u git://github.com/mt8163/android.git -b lineage-15.1

but this one fails with:

    frameworks/av/media/libstagefright/colorconversion/ColorConverter.cpp:71:17: error: use of undeclared identifier 'OMX_MTK_COLOR_FormatYV12'

Multiple OMX_MTK/OMX_COLOR constants are not being found.

**Comment by jmpfbmx** [comment]
Hi
How are you?
For build for freezerfhd you need to build with LineageOS source not mt8163 one.
`repo init -u git://github.com/LineageOS/android.git -b lineage-15.1 && repo sync -f --force-sync`
If you want i can make for you a script for building for freezerfhd
Thanks,
Regards Jose

**Comment by RobertZenz** [comment]
Okay, in that case there still is that missing xlog problem, which feels like I've missed something important somewhere but I don't know what. I actually tried to copy libxlog from another device, but that turned out...not so great (for once, it did not boot but failed with another missing symbol, and my device stopped booting at all after that).

I'll check my set up again, but I'd like to see a script or updated build instructions if you've got the time.

**Comment by R0rt1z2** [comment]
> Okay, in that case there still is that missing xlog problem, which feels like I've missed something important somewhere but I don't know what. I actually tried to copy libxlog from another device, but that turned out...not so great (for once, it did not boot but failed with another missing symbol, and my device stopped booting at all after that).
> 
> I'll check my set up again, but I'd like to see a script or updated build instructions if you've got the time.

Make sure to apply all the patches (I just pushed a commit that fixes the sh scripts for applying them):
```sh vendor/bq/mt8163/build/patches/install.sh```
After aplying those, try to rebuild again and check if you still get missing symbols.

**Comment by RobertZenz** [comment]
That's a very good hint, thank you.

**Comment by jmpfbmx** [comment]
Here you are @RobertZenz 
`
#!/bin/bash
echo "We are gonna sync LineageOS 15.1 Source"
mkdir LOS15.1 && cd LOS15.1 && repo init -u git://github.com/LineageOS/android.git -b lineage-15.1 && repo sync -f --force-sync
echo "We are gonna clone device tree, kernel source and vendor blobs"
git clone -b lineage-15.1 https://github.com/mt8163/android_device_bq_freezerfhd device/bq/freezerfhd && git clone -b lineage-15.1 https://github.com/mt8163/android_device_bq_aquaris_m8 device/bq/aquaris_m8 && git clone -b lineage-15.1 https://github.com/mt8163/android_kernel_bq_freezerfhd kernel/bq/freezerfhd && git clone -b lineage-15.1 https://github.com/mt8163/android_vendor_bq_freezerfhd vendor/bq/freezerfhd && git clone -b lineage-15.1 https://github.com/mt8163/android_vendor_bq_mt8163/ vendor/bq/mt8163
echo "We are gonna apply patches"
chmod a+x vendor/bq/mt8163/build/patches/install.sh && ./vendor/bq/mt8163/build/patches/install.sh
echo "We are gonna start building"
. build/envsetup.sh && lunch lineage_freezerfhd-userdebug && brunch lineage_freezerfhd-userdebug
`

**Comment by R0rt1z2** [comment]
> Here you are @RobertZenz
> `#!/bin/bash echo "We are gonna sync LineageOS 15.1 Source" mkdir LOS15.1 && cd LOS15.1 && repo init -u git://github.com/LineageOS/android.git -b lineage-15.1 && repo sync -f --force-sync echo "We are gonna clone device tree, kernel source and vendor blobs" git clone -b lineage-15.1 https://github.com/mt8163/android_device_bq_freezerfhd device/bq/freezerfhd && git clone -b lineage-15.1 https://github.com/mt8163/android_device_bq_aquaris_m8 device/bq/aquaris_m8 && git clone -b lineage-15.1 https://github.com/mt8163/android_kernel_bq_freezerfhd kernel/bq/freezerfhd && git clone -b lineage-15.1 https://github.com/mt8163/android_vendor_bq_freezerfhd vendor/bq/freezerfhd && git clone -b lineage-15.1 https://github.com/mt8163/android_vendor_bq_mt8163/ vendor/bq/mt8163 echo "We are gonna apply patches" chmod a+x vendor/bq/mt8163/build/patches/install.sh && ./vendor/bq/mt8163/build/patches/install.sh echo "We are gonna start building" . build/envsetup.sh && lunch lineage_freezerfhd-userdebug && brunch lineage_freezerfhd-userdebug`

I don't think nobody needs a build script as we already have one: https://github.com/mt8163/android_vendor_bq_mt8163/blob/lineage-15.1/build/build.sh

**Comment by jmpfbmx** [comment]
> 
> 
> > Here you are @RobertZenz
> > `#!/bin/bash echo "We are gonna sync LineageOS 15.1 Source" mkdir LOS15.1 && cd LOS15.1 && repo init -u git://github.com/LineageOS/android.git -b lineage-15.1 && repo sync -f --force-sync echo "We are gonna clone device tree, kernel source and vendor blobs" git clone -b lineage-15.1 https://github.com/mt8163/android_device_bq_freezerfhd device/bq/freezerfhd && git clone -b lineage-15.1 https://github.com/mt8163/android_device_bq_aquaris_m8 device/bq/aquaris_m8 && git clone -b lineage-15.1 https://github.com/mt8163/android_kernel_bq_freezerfhd kernel/bq/freezerfhd && git clone -b lineage-15.1 https://github.com/mt8163/android_vendor_bq_freezerfhd vendor/bq/freezerfhd && git clone -b lineage-15.1 https://github.com/mt8163/android_vendor_bq_mt8163/ vendor/bq/mt8163 echo "We are gonna apply patches" chmod a+x vendor/bq/mt8163/build/patches/install.sh && ./vendor/bq/mt8163/build/patches/install.sh echo "We are gonna start building" . build/envsetup.sh && lunch lineage_freezerfhd-userdebug && brunch lineage_freezerfhd-userdebug`
> 
> I don't think nobody needs a build script as we already have one: https://github.com/mt8163/android_vendor_bq_mt8163/blob/lineage-15.1/build/build.sh

Oh true i didn't remember that, but well if he wants an automated script that makes the whole process he can use the one I made right now.

**Comment by RobertZenz** [comment]
Thanks, I'll retry with that and report back.

**Comment by RobertZenz** [comment]
Thanks, that did it, it worked.
